### ISSUE TITLE
Flux of SUN dependency on chunking (nchan) and clean threshold.

### ISSUE THREAD

**Issue by abhisek176** [ratt-ru/solarkat#35]
Hi Victoria et al.,

I am trying to use solarkat for our LADUMA UHF day tracks. I would like to know some more details about a few of the hard-coded values chosen in the pipeline recipe file ​​https://github.com/ratt-ru/solarkat/blob/main/solarkat-pipeline/solarkat.yaml. 
Many thanks to @IanHeywood for some insights on the intial results. 

1. deconvolve-sun: 

- **nchan = 8** : We noticed that varying the chunking significantly affects the flux of the sun from the MFS images. For instance, using nchan = 2 results in nearly _double the flux_ compared to nchan = 8, despite keeping the same threshold and niter as (b). In summary, higher residuals if we use larger chunking (smaller bandwidth).
- **threshold: 3.55e-4 & niter: 10000**: I saw some discussions (issues #22, 24, 26) regarding this. I’m curious if there’s an automated method to set this threshold. For example, would higher iterations with auto-threshold (0.5 to 1 sigma) suffice for most fields, or how should these values be set for tracks taken at different times and durations? – I think 1(a) is related to this!

2. Mask-2:

- **threshold: 15**: Isn’t this value slightly high to include all genuine signals in the mask, which is necessary for predicting accurate MODEL_DATA? Is there a particular reason for selecting higher threshold values in the mask cabs?

3. cal-and-peel-sun:

- Input_model.recipe: Instead of using subtract-sun:image-6 and re-modeling the CORRECTED_DATA_SUN, is it possible to use MODEL_DATA_ORIGINAL~MODEL_DATA_SUN:MODEL_DATA_SUN in quartical?

Thank you very much for this fantastic package!

**Comment by Victoria-Samboco** [comment]
Hi @abhisek176,

Thanks for reaching out. Some of the questions here were already clarified in our in-person chat at the GA. however, I will leave some comments/explanations if someone else has the same questions.

1. The threshold of 3.55e-4 was hard-coded for a specific dataset based on its rms. It can be modified for each dataset depending on the observing frequency. But I believe an automated method such as using the values you mention can work (as it did for you). I will do some tests to ensure it works in all cases.

2. For the mask-2 step (and other masking steps), threshold values largely depend on our specific science goals. In this case, the objective was to effectively subtract the Sun’s emission to improve the overall image quality, particularly in reducing solar interference, without significantly affecting the flux measurements of the primary field of interest. So, this is part of the calibration process, and most of the parameters there, including the decision to perform the DD calibration or not, will depend solely on your data and goals. So yes, a lower threshold might be more appropriate if your goal involves detecting fainter sources or conducting a detailed analysis of less prominent features. This would allow the mask to include more genuine signals, preserving them for further analysis. 

3. About point 3, I never thought about that, but I think it is something worth trying.  It can reduce some steps, reducing the processing time. Please let me know if you did try it and if it works.

**Comment by abhisek176** [comment]
Hi @Victoria-Samboco:

Thanks very much! Yes, I did try (3) and it seems working the same and hence reduced several steps.

**Comment by Victoria-Samboco** [comment]
That's great, thank you very much for your feedback, l will take it in account when I am  working towards the pipeline optimization. -------- Original message --------From: Abhisek Mohapatra ***@***.***>Date: Fri, 30 Aug 2024, 04:40To: ratt-ru/solarkat ***@***.***>Cc: Victoria-Samboco ***@***.***>, Mention ***@***.***>Subject: Re: [ratt-ru/solarkat] Flux of SUN dependency on chunking (nchan) and clean threshold. (Issue #35)
Hi @Victoria-Samboco:
Thanks very much! Yes, I did try (3) and it seems working the same and hence reduced several steps.
